### ISSUE TITLE
Putting files inside a subfolder makes the subfoler into a zip?????

### ISSUE THREAD

**Issue by Billybobertjoe** [solosky/pixl.js#111] opened 2023-08-30 16:10 UTC
![image](https://github.com/solosky/pixl.js/assets/70166353/e53fe2ce-0a96-4880-ad35-62ddd7fa2fa8)

**Comment by solosky** [comment] 2023-08-31 04:45
Hi sir, 

Please provide more information here, for example,

* Detail steps to produce this issue 
* What is expected behavior 
* What is ectual behavior 

it is even better if you post screenshots or demo videos here.

**Comment by Billybobertjoe** [comment] 2023-09-02 15:52
I go to iNFC app and connect to the pixl.js and create a folder inside the amiibo folder. I then create another folder inside that. I then create another folder inside that. I then place the FOLDER containing the amiibo bin files inside that folder. That usually causes the pixl.js to make the FOLDER into a zip?

**Comment by solosky** [comment] 2023-09-02 15:58
Actually, I dont understand 'make the FOLDER into a zip', can you explain more about this ?

**Comment by Billybobertjoe** [comment] 2023-09-02 16:06
> ![image](https://github.com/solosky/pixl.js/assets/70166353/e53fe2ce-0a96-4880-ad35-62ddd7fa2fa8)

Like this.

**Comment by Billybobertjoe** [comment] 2023-09-02 16:07
The "amiibo figures" file is supposed to be a folder.

**Comment by Billybobertjoe** [comment] 2023-09-02 16:09
It is turning it into a file of some kind instead of keeping it as a folder

**Comment by solosky** [comment] 2023-09-02 16:22
Oh, I get your point, the fact is that the Pixl.js file system has limitation on its full file path for a file, like /amiibo/animalcrossing/amiibo1.bin. The total length of the file should not be exceed 64 characters, and file/folder name should not be exceed 48 characters. This limitation is introduced by SPIFFS file system. 
```
#define VFS_MAX_NAME_LEN 48
#define VFS_MAX_PATH_LEN 64
#define VFS_MAX_META_LEN 128
```

Please shorten your folder name and file name, and keep the folder count minimum as you can. 

Meanwhile, you can use iNFC update to latest 2.8.3, it introduce a new app called Amiibo Database with almost all amiibo files built in, you can have a try. 

Please let me know if you have more questions.

**Comment by solosky** [comment] 2023-09-02 16:24
I think I will impove the error prompt in future release, sorry to make your confused.

**Comment by Billybobertjoe** [comment] 2023-09-02 16:34
Ok thank youSent from my iPhoneOn Sep 2, 2023, at 9:24 AM, solosky ***@***.***> wrote:﻿
I think I will impove the error prompt in future release, sorry to make your confused.

**Comment by solosky** [comment] 2023-10-19 09:28
Close the issue since there is no furthermore comments from user.

**Closed by solosky** 2023-10-19 09:28 UTC

**Comment by Billybobertjoe** [comment] 2023-12-03 19:53
Another issue I am having with this is if I try to put all of the animal crossing amiibo .bin in a single folder, the device just crashes right when I try to enter that folder on the device. I don’t know how to fix that due to the issue we were talking about. 

> Oh, I get your point, the fact is that the Pixl.js file system has limitation on its full file path for a file, like /amiibo/animalcrossing/amiibo1.bin. The total length of the file path string should not be exceed 64 characters, and file/folder name should not be exceed 48 characters. This limitation is introduced by SPIFFS file system.
> 
> ```
> #define VFS_MAX_NAME_LEN 48
> #define VFS_MAX_PATH_LEN 64
> #define VFS_MAX_META_LEN 128
> ```
> 
> Please shorten your folder name and file name, and keep the folder count minimum as you can.
> 
> Meanwhile, you can use iNFC update to latest firmware 2.8.3, it introduce a new app called Amiibo Database with almost all amiibo files built in, you can have a try.
> 
> Please let me know if you have more questions.
